project:
  type: website

website:
  title: "CA2_SQL_LinearRegression"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: technologyexploration.qmd
        text: Technology Exploration
      - href: about.qmd
        text: References
      - href: Projectconclusions.qmd
        text: Project Conclusions

format:
  html:
    theme: cosmo
    css: styles.css

editor: source

