project:
  type: website

website:
  title: "2023_DAIE_ICA_1_ET"
  navbar:
    left:
      - href: index.qmd
        text: SQL and Linear Regression
      - href: technologyexploration.qmd
        text: Technology Exploration
      - href: Projectconclusions.qmd
        text: Project Conclusions
      - href: about.qmd
        text: References

format:
  html:
    theme: cosmo
    css: styles.css

editor: source

